/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.santo.terco.novena;

import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Named;
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Felipe
 */
@Named
@SessionScoped
@Getter
@Setter
public class NovenaNossaSenhoraConceicaoBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private String nome = "Novena de Nossa Senhora da Conceição";

    private String periodo = "Normalmente feita dos dias 03 de outubro à 11 de outubro.";

    private String motivo = "Rezar a Novena à Imaculada é uma forma carinhosa de expressar nosso amor por Ela e de caminhar ao seu lado. Durante nove dias, vamos desejar a beleza, contemplar Aquela que é toda bela, toda pura, toda de Deus, e procurar imitá-la. Assim, seguiremos nosso caminho de fé com Aquela que pôde dizer de si mesma: “Eu sou a Imaculada Conceição!”";

    private String palavrasPapa = "“Olhando para Nossa Senhora, como não deixar despertar em nós, seus filhos, a aspiração à beleza, à bondade, à pureza do coração? A sua celeste candura nos atrai a Deus, ajudando-nos a superar a tentação de uma vida medíocre, feita de compromissos com o mal, para orientar-nos decididamente para um autêntico bem, que é fonte de alegria”. (Bento XVI, 08.12.2005)";

    private String gracas = "As graças:\n"
            + "\n"
            + "Alcançai-me principalmente estas graças:\n"
            + "\n"
            + "- A primeira, não cometer jamais pecado mortal;\n"
            + "\n"
            + "- A segunda, um grande apreço da virtude cristã;\n"
            + "\n"
            + "- A terceira, uma boa morte.\n"
            + "\n"
            + "Além disso, dai-me a graça particular que vos peço especialmente nesta novena. (Fazer aqui o pedido particular que se deseja obter)";

    private String primeiroDia = "A Virgem Maria, Mãe de Deus\n"
            + "\n"
            + "Entrando o Anjo disse-lhe “Ave ‘Cheia de Graça’ o Senhor é contigo” (Lc1,28)\n"
            + "\n"
            + "“Maria recebe a vida d'Aquele, ao qual ela própria, na ordem da geração terrena, deu a vida como mãe. E, uma vez que Maria recebe esta ‘vida nova’ numa plenitude correspondente ao amor do Filho para com a Mãe, e em consequência à dignidade da maternidade divina, o Anjo na Anunciação chama-lhe ‘cheia de graça’”.(RM 10).\n"
            + "\n"
            + "A excelsa grandeza sobrenatural foi concedida a Nossa Senhora em referência a Jesus Cristo; é nEle e mediante ele que Deus lhe participou a plenitude de santidade: “Maria é Imaculada porque é Mãe de Deus e torna-se Mãe de Deus porque é Imaculada. Da maternidade divina jorram todas as graças concedidas à Santíssima Virgem Maria e a primeira dessas é a Imaculada Conceição”. (EK 1210).\n"
            + "\n"
            + "Oremos: (Oração inicial)\n"
            + "\n"
            + "Adoro-te, ó Pai nosso celeste, porque depuseste no seio puríssimo da Imaculada o teu Filho Unigênito.\n"
            + "\n"
            + "Adoro-te, ó Filho de Deus, porque te dignaste entrar no seio de Maria e te tornaste verdadeiro, real Filho seu.\n"
            + "\n"
            + "Adoro-te, ó Espírito Santo, porque te dignastes formar no seio Imaculado dEla o corpo do Filho de Deus.\n"
            + "\n"
            + "Adoro-te, ó Trindade Santíssima, ó Deus Uno na Santa Trindade, por ter enaltecido a Imaculada de um modo tão divino.\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo, como era no princípio, agora e sempre. Amém!\n"
            + "\n"
            + "Vamos dirigir nossos pedidos à Imaculada, nossa mãe amorosa, que está sempre pronta a escutar e acompanhar seus filhos:\n"
            + "\n"
            + "1 – Mãe querida, te pedimos por todos os que estão afastados da vida da Graça, para que sintam saudade do colo Materno e busquem a tua proteção, nós te pedimos,\n"
            + "\n"
            + "R. Virgem Maria, Mãe de Deus, rogai por nós!\n"
            + "\n"
            + "2 – Por todos nós, teus filhos, para que estejamos sempre abertos à graça de Deus, nós te pedimos,\n"
            + "\n"
            + "R. Virgem Maria, Mãe de Deus, rogai por nós!\n"
            + "\n"
            + "3 – Por todos que trabalham e se sacrificam pela Evangelização, para que sejam recompensados em sua generosidade, nós te pedimos,\n"
            + "\n"
            + "R. Virgem Maria, Mãe de Deus, rogai por nós!\n"
            + "\n"
            + "Pai Nosso...\n"
            + "\n"
            + "Ave Maria...\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo...\n"
            + "\n"
            + "O Maria concebida sem pecado, rogai por nós que recorremos a vós e por todos quantos não recorrem a vós, especialmente pelos inimigos da Santa Igreja e por todos quantos são a vós recomendados.\n"
            + "\n"
            + "Oremos: (Oração final)\n"
            + "\n"
            + "Sob a tua proteção, ó Mãe dulcíssima, e com a invocação do mistério da tua Imaculada Conceição, desejo realizar todos os meus atos e suportar tudo o que me aconteça. Além disso, prometo contribuir, com todas as energias à minha disposição, para render a Deus o culto devido, por meio da difusão da devoção a Ti. Peço-te, portanto, ó Mãe amorosíssima, que te dignes ajudar-me em minhas fadigas. De minha parte, prometo, devota e livremente, como é justo, reconhecer como obtido de Deus por tua intercessão qualquer benefício que resulte das minhas atividades.\n"
            + "\n"
            + "Concede-me louvar-te, ó Virgem Santíssima; e dá-me força contra os teus inimigos! (EK 1353)\n"
            + "\n"
            + "Louvado Seja Nosso Senhor Jesus Cristo...\n"
            + "\n"
            + "Salve Maria Imaculada";

    private String segundoDia = "A Virgem Maria, Medianeira das Graças\n"
            + "\n"
            + "“Disse, então, sua mãe aos serventes: ‘Fazei o que ele vos disser’”. (Jo 2,5)\n"
            + "\n"
            + "\"A função maternal de Maria para com os homens não obscurece nem diminui a única mediação de Cristo, mas mostra sua eficácia. Qualquer influxo salvador da Santíssima Virgem nasce da permissão divina e deriva da superabundância dos méritos de Cristo\" (LG,n.60).\n"
            + "\n"
            + "A maternidade de Maria na economia da graça perdura sem interrupção... Depois de elevada ao céu, não abandonou esta missão salvadora, mas, com a sua multiforme intercessão, continua a alcançar-nos os dons da salvação eterna. Cuida, com amor materno, dos irmãos de seu Filho que, entre perigos e angústias, caminham ainda na terra, até chegarem à pátria bem-aventurada. Por isso, a Virgem é invocada na Igreja com os títulos de advogada, auxiliadora, socorro, medianeira.\n"
            + "\n"
            + "Oremos: (Oração inicial)\n"
            + "\n"
            + "Adoro-te, ó Pai nosso celeste, porque depuseste no seio puríssimo da Imaculada o teu Filho Unigênito.\n"
            + "\n"
            + "Adoro-te, ó Filho de Deus, porque te dignaste entrar no seio de Maria e te tornaste verdadeiro, real Filho seu.\n"
            + "\n"
            + "Adoro-te, ó Espírito Santo, porque te dignastes formar no seio Imaculado dEla o corpo do Filho de Deus.\n"
            + "\n"
            + "Adoro-te, ó Trindade Santíssima, ó Deus Uno na Santa Trindade, por ter enaltecido a Imaculada de um modo tão divino.\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo, como era no princípio, agora e sempre. Amém!\n"
            + "\n"
            + "Vamos dirigir nossos pedidos à Imaculada, nossa mãe amorosa, que está sempre pronta a escutar e acompanhar seus filhos:\n"
            + "\n"
            + "1 – Mãe querida, nas dificuldades, nos perigos e incertezas da vida, faça acontecer o teu influxo materno sobre nós e sobre as circunstâncias que se apresentam, nos te pedimos,\n"
            + "\n"
            + "R. Virgem Maria, Medianeira das Graças, rogai por nós!\n"
            + "\n"
            + "2 – Para que todos nós, alcancemos as graças que precisamos no empenho pela nossa salvação e de nossos irmãos, nos te pedimos,\n"
            + "\n"
            + "R. Virgem Maria, Medianeira das Graças, rogai por nós!\n"
            + "\n"
            + "3 – Ó Imaculada, interceda para que cada consagrado a Ti alcance a eficácia pastoral e dignamente anuncie o teu Nome, e a salvação em Jesus Cristo, nós te pedimos,\n"
            + "\n"
            + "R. Virgem Maria, Medianeira das Graças, rogai por nós!";

    private String terceiroDia = "Santa Maria, a Virgem a escuta\n"
            + "\n"
            + "\"Maria, porém, guardava todas essas coisas e sobre elas refletia em seu coração. (LC 2,19)\n"
            + "\n"
            + "“Maria é a Virgem em escuta que acolhe a Palavra de Deus com fé”. (MC 17). No evangelho contemplamos Maria como a Virgem em escuta, que fez da sua vida um contínuo “sim” à vontade de Deus. “Na anunciação, Maria se abandonou a Deus completamente, manifestando a ‘obediência da fé’ Àquele que lhe falava mediante o seu mensageiro” (conf. RM 13).\n"
            + "\n"
            + "A contemplação e a íntima união com Maria, a Virgem da escuta, a Virgem em oração, a Virgem mãe e a Virgem oferente, pode nos conduzir a testemunhar a mensagem do Evangelho na nossa vida. Sim, também nós, devemos olhar para Maria e fazer como ela, da nossa vida um culto a Deus e de tal culto um empenho de vida, que consiste em fazer a vontade de Deus. Sempre. Em toda parte. Também na dor. Também na morte.\n"
            + "\n"
            + "Oremos: (Oração inicial)\n"
            + "\n"
            + "Adoro-te, ó Pai nosso celeste, porque depuseste no seio puríssimo da Imaculada o teu Filho Unigênito.\n"
            + "\n"
            + "Adoro-te, ó Filho de Deus, porque te dignaste entrar no seio de Maria e te tornaste verdadeiro, real Filho seu.\n"
            + "\n"
            + "Adoro-te, ó Espírito Santo, porque te dignastes formar no seio Imaculado dEla o corpo do Filho de Deus.\n"
            + "\n"
            + "Adoro-te, ó Trindade Santíssima, ó Deus Uno na Santa Trindade, por ter enaltecido a Imaculada de um modo tão divino.\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo, como era no princípio, agora e sempre. Amém!\n"
            + "\n"
            + "Vamos dirigir nossos pedidos à Imaculada, nossa mãe amorosa, que está sempre pronta a escutar e acompanhar seus filhos:\n"
            + "\n"
            + "1 – Mãe querida, coloque no coração de todos os teus filhos o desejo de escutar, meditar e colocar em prática os ensinamentos de teu Divino Filho, nós te pedidos,\n"
            + "\n"
            + "R. Santa Maria, a Virgem a escuta, rogai por nós!\n"
            + "\n"
            + "2 – Por todos aqueles que estão unidos à Milícia da Imaculada, para que ouvindo a Palavra de Deus, acolham e imitem a Tua atitude de escuta, nós te pedimos,\n"
            + "\n"
            + "R. Santa Maria, a Virgem a escuta, rogai por nós!\n"
            + "\n"
            + "3 – Por todos nós, para que imitando teu exemplo, abramos os horizontes do nosso coração à escuta permitindo-nos uma vida nova, nos te pedimos,\n"
            + "\n"
            + "R. Santa Maria, a Virgem a escuta, rogai por nós!\n"
            + "\n"
            + "Pai Nosso...\n"
            + "\n"
            + "Ave Maria...\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo...\n"
            + "\n"
            + "Oh Maria concebida sem pecado, rogai por nós que recorremos a vós e por todos quantos não recorrem a vós, especialmente pelos inimigos da Santa Igreja e por todos quantos são a vós recomendados.\n";

    private String quartoDia = "A Virgem Maria, Mãe do Redentor\n"
            + "\n"
            + "“Deus enviou seu Filho, que nasceu de uma mulher...a fim de remir os que estavam sob a Lei, para que recebêssemos a sua adoção” (Gal. 4,4)\n"
            + "\n"
            + "“A Imaculada é nossa mãe porque Jesus a deu a nós... É mãe do Redentor, portanto, também dos redimidos. Ama-a como mãe. Ela te ama a ponto de sacrificar o Filho de Deus; na anunciação te acolheu de bom grado como filho. Ela te tornará semelhante a si mesma, te tornará sempre mais imaculado. Deixa-te conduzir por ela, deixa-te plasmar sempre mais livremente por ela”. (EK 1334).\n"
            + "\n"
            + "Declarando-se serva daquele Deus que se fez Servo e que veio em nosso meio para não ser servido, mas para servir. “As palavras: ‘Eis aqui a serva do Senhor!’ comprovam o fato dela desde o princípio ter aceitado e entendido a própria maternidade como dom total de si, da sua pessoa, a serviço dos desígnios salvíficos do Altíssimo.” (RM, 39).\n"
            + "\n"
            + "Oremos: (Oração inicial)\n"
            + "\n"
            + "Sob a tua proteção, ó Mãe dulcíssima, e com a invocação do mistério da tua Imaculada Conceição, desejo realizar todos os meus atos e suportar tudo o que me aconteça. Além disso, prometo contribuir, com todas as energias à minha disposição, para render a Deus o culto devido, por meio da difusão da devoção a Ti. Peço-te, portanto, ó Mãe amorosíssima, que te dignes ajudar-me em minhas fadigas. De minha parte, prometo, devota e livremente, como é justo, reconhecer como obtido de Deus por tua intercessão qualquer benefício que resulte das minhas atividades.\n"
            + "\n"
            + "Concede-me louvar-te, ó Virgem Santíssima; e dá-me força contra os teus inimigos! (EK 1353)\n"
            + "\n"
            + "Vamos dirigir nossos pedidos à Imaculada, nossa mãe amorosa, que está sempre pronta a escutar e acompanhar seus filhos:\n"
            + "\n"
            + "1 – Mãe querida, alcança de nós os favores que necessitamos para alcançarmos a remissão de todos os nossos pecados, nós te pedimos,\n"
            + "\n"
            + "R.: Virgem Maria, Mãe do Redentor, rogai por nós!\n"
            + "\n"
            + "2 – Por todos os cristãos, para que sintam a alegria de poder contar com a tua proteção materna e assim sigam perseverantes para meta final, nós te pedimos,\n"
            + "\n"
            + "R.: Virgem Maria, Mãe do Redentor, rogai por nós!\n"
            + "\n"
            + "3 – Pela Milicia da Imaculada, para que receba sempre os recursos necessários para propagar a certeza da salvação em Jesus Cristo, nosso Redentor, nós te pedimos,\n"
            + "\n"
            + "R.: Virgem Maria, Mãe do Redentor, rogai por nós!\n"
            + "\n"
            + "Pai Nosso...\n"
            + "\n"
            + "Ave Maria...\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo...\n"
            + "\n"
            + "O Maria concebida sem pecado, rogai por nós que recorremos a vós e por todos quantos não recorrem a vós, especialmente pelos inimigos da Santa Igreja e por todos quantos são a vós recomendados.\n"
            + "\n"
            + "Oremos: (Oração final)\n"
            + "\n"
            + "Sob a tua proteção, ó Mãe dulcíssima, e com a invocação do mistério da tua Imaculada Conceição, desejo realizar todos os meus atos e suportar tudo o que me aconteça. Além disso, prometo contribuir, com todas as energias à minha disposição, para render a Deus o culto devido, por meio da difusão da devoção a Ti. Peço-te, portanto, ó Mãe amorosíssima, que te dignes ajudar-me em minhas fadigas. De minha parte, prometo, devota e livremente, como é justo, reconhecer como obtido de Deus por tua intercessão qualquer benefício que resulte das minhas atividades.\n"
            + "\n"
            + "Concede-me louvar-te, ó Virgem Santíssima; e dá-me força contra os teus inimigos! (EK 1353)";

    private String quintoDia = "A Virgem Maria, ventre Eucarístico\n"
            + "\n"
            + "“E o Verbo se fez carne e habitou entre nós, e vimos sua glória” (Jo 1,14).\n"
            + "\n"
            + "“Ao se cumprir o tempo da vinda de Cristo, Deus uno e trino cria exclusivamente para si a Virgem Imaculada, a cheia de graça e habita nela (‘O Senhor é contigo’ Lc 1,28). E esta Virgem Santíssima com a própria humildade fascina de tal modo o Seu Coração que Deus Pai Lhe dá por filho o seu próprio Filho Unigênito, Deus Filho desce no Seu ventre virginal, enquanto que Deus Espírito Santo plasma nela o corpo santíssimo do Homem-Deus. E o Verbo se fez carne (Jo 1,14) como fruto do amor de Deus e da Imaculada”. (EK 1296)\n"
            + "\n"
            + "“O Verbo revestiu-se de uma carne Santa que tomou emprestada da Virgem Maria, para unir o nosso corpo mortal ao seu poder Divino” (Santo Hipólito)\n"
            + "\n"
            + "A Virgem Maria, reunindo ao seu redor a “nova” humanidade nascida da celebração da Eucaristia e fazendo-se acolher como Mãe dom do Filho: “Viver na Eucaristia o memorial da morte de Cristo implica também em receber continuamente este dom ...aquela que toda vez nos é doada como Mãe” (Ecclesia de Eucharistia, 57).\n"
            + "\n"
            + "Oremos: (Oração inicial)\n"
            + "\n"
            + "Adoro-te, ó Pai nosso celeste, porque depuseste no seio puríssimo da Imaculada o teu Filho Unigênito.\n"
            + "\n"
            + "Adoro-te, ó Filho de Deus, porque te dignaste entrar no seio de Maria e te tornaste verdadeiro, real Filho seu.\n"
            + "\n"
            + "Adoro-te, ó Espírito Santo, porque te dignastes formar no seio Imaculado dEla o corpo do Filho de Deus.\n"
            + "\n"
            + "Adoro-te, ó Trindade Santíssima, ó Deus Uno na Santa Trindade, por ter enaltecido a Imaculada de um modo tão divino.\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo, como era no princípio, agora e sempre. Amém!\n"
            + "\n"
            + "Vamos dirigir nossos pedidos à Imaculada, nossa mãe amorosa, que está sempre pronta a escutar e acompanhar seus filhos:\n"
            + "\n"
            + "1 – Mãe Querida, permaneça conosco quando nos aproximamos da Santa Eucaristia, para que possamos receber dignamente Teu filho, nós te pedimos,\n"
            + "\n"
            + "R.: Virgem Maria, ventre Eucarístico, rogai por nós!\n"
            + "\n"
            + "2 – Pelos milites do mundo inteiro, para encontrem na Eucaristia o alimento essencial para sua vida, nós te pedimos,\n"
            + "\n"
            + "R.: Virgem Maria, ventre Eucarístico, rogai por nós!\n"
            + "\n"
            + "3 – Por todos os sacerdotes para que sejam amparados por Ti e mantenham-se perseverantes em sua bela missão eucarística, nós te pedimos,\n"
            + "\n"
            + "R.: Virgem Maria, ventre Eucarístico, rogai por nós!\n"
            + "\n"
            + "Pai Nosso...\n"
            + "\n"
            + "Ave Maria...\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo...\n"
            + "\n"
            + "Oh Maria concebida sem pecado, rogai por nós que recorremos a vós e por todos quantos não recorrem a vós, especialmente pelos inimigos da Santa Igreja e por todos quantos são a vós recomendados.\n"
            + "\n"
            + "Oremos: (Oração final)\n"
            + "\n"
            + "Sob a tua proteção, ó Mãe dulcíssima, e com a invocação do mistério da tua Imaculada Conceição, desejo realizar todos os meus atos e suportar tudo o que me aconteça. Além disso, prometo contribuir, com todas as energias à minha disposição, para render a Deus o culto devido, por meio da difusão da devoção a Ti. Peço-te, portanto, ó Mãe amorosíssima, que te dignes ajudar-me em minhas fadigas. De minha parte, prometo, devota e livremente, como é justo, reconhecer como obtido de Deus por tua intercessão qualquer benefício que resulte das minhas atividades.\n"
            + "\n"
            + "Concede-me louvar-te, ó Virgem Santíssima; e dá-me força contra os teus inimigos! (EK 1353)";

    private String sextoDia = "Maria, a Virgem feita Igreja\n"
            + "\n"
            + "“Todos eles perseveravam unanimemente na oração, juntamente com as mulheres, entre elas Maria, mãe de Jesus, e os irmãos dele” (At1, 14)\n"
            + "\n"
            + "“Depois que o Senhor nosso Jesus Cristo, vence a morte, ressuscitou e subiu ao céu, se reuniu então a Igreja no cômodo do piso superior junto com Maria, a Mãe de Jesus. Não se pode falar de Igreja se não estiver presente Maria, Mãe do Senhor, junto aos seus irmãos” (Cromásio, Discorsi, 30,1).\n"
            + "\n"
            + "“Maria é a presença orante na Igreja nascente e na Igreja de todo tempo, porque Ela, assunta ao céu, não terminou a sua missão de intercessão e de salvação.” (MC 18.)\n"
            + "\n"
            + "João Paulo II evidenciou a importância do princípio mariano na Igreja dizendo: “Tudo na Igreja, qualquer instituição e ministério, também o de Pedro e dos seus sucessores, está \"incluído\" sob o manto da Virgem, no espaço pleno da graça do seu \"sim\" à vontade de Deus. Entre Maria e a Igreja existe de fato a mesma naturalidade”.\n"
            + "\n"
            + "Oremos: (Oração inicial)\n"
            + "\n"
            + "Adoro-te, ó Pai nosso celeste, porque depuseste no seio puríssimo da Imaculada o teu Filho Unigênito.\n"
            + "\n"
            + "Adoro-te, ó Filho de Deus, porque te dignaste entrar no seio de Maria e te tornaste verdadeiro, real Filho seu.\n"
            + "\n"
            + "Adoro-te, ó Espírito Santo, porque te dignastes formar no seio Imaculado dEla o corpo do Filho de Deus.\n"
            + "\n"
            + "Adoro-te, ó Trindade Santíssima, ó Deus Uno na Santa Trindade, por ter enaltecido a Imaculada de um modo tão divino.\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo, como era no princípio, agora e sempre. Amém!\n"
            + "\n"
            + "Vamos dirigir nossos pedidos à Imaculada, nossa mãe amorosa, que está sempre pronta a escutar e acompanhar seus filhos:\n"
            + "\n"
            + "1 – Mãe Querida, mantenha a Igreja de teu Filho, sob teu manto materno para que siga amparada por tua ternura, nós te pedimos,\n"
            + "\n"
            + "R.: Maria, Virgem feita Igreja, rogai por nós!\n"
            + "\n"
            + "2 – Por todos os sacerdotes, diáconos, ministros, missionários e missionárias para que sejam fieis à missão assumida por amor a teu Filho, e possam afirmar como tu, “eis aqui a serva, o servo do Senhor, nós te pedimos,\n"
            + "\n"
            + "R.: Maria, Virgem feita Igreja, rogai por nós!\n"
            + "\n"
            + "3 – Pela Milícia da Imaculada para que, por tua intercessão, continue a trabalhar pela Igreja, com a Igreja e em nome da Igreja, nós te pedimos,\n"
            + "\n"
            + "R.: Maria, Virgem feita Igreja, rogai por nós!\n"
            + "\n"
            + "Pai Nosso...\n"
            + "\n"
            + "Ave Maria...\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo...\n"
            + "\n"
            + "Oh Maria, concebida sem pecado, rogai por nós que recorremos a vós e por todos quantos não recorrem a vós, especialmente pelos inimigos da Santa Igreja e por todos quantos são a vós recomendados.\n"
            + "\n"
            + "Oremos: (Oração final)\n"
            + "\n"
            + "Sob a tua proteção, ó Mãe dulcíssima, e com a invocação do mistério da tua Imaculada Conceição, desejo realizar todos os meus atos e suportar tudo o que me aconteça. Além disso, prometo contribuir, com todas as energias à minha disposição, para render a Deus o culto devido, por meio da difusão da devoção a Ti. Peço-te, portanto, ó Mãe amorosíssima, que te dignes ajudar-me em minhas fadigas. De minha parte, prometo, devota e livremente, como é justo, reconhecer como obtido de Deus por tua intercessão qualquer benefício que resulte das minhas atividades.\n"
            + "\n"
            + "Concede-me louvar-te, ó Virgem Santíssima; e dá-me força contra os teus inimigos! (EK 1353)";

    private String setimoDia = "Maria, Modelo de vida evangélica\n"
            + "\n"
            + "“Mulher, eis o teu filho”, “Filho, eis a tua mãe”. E daquele momento em diante o discípulo a levou para sua casa” (Jo 19, 25-27).\n"
            + "\n"
            + "Quando Jesus disse sobre a Cruz: “Mulher, eis o teu filho” (Jo 19,26), de modo novo abre o Coração de sua Mãe, o Coração Imaculado, e revelou-lhe a nova dimensão do amor e a carga do amor, à qual era chamada no Espírito Santo com a força do sacrifício da Cruz.\n"
            + "\n"
            + "A sua presença, por desígnio de Deus, é determinante e necessária para a vida dos fieis portanto da Igreja, mesmo quando é ignorada ou descumprida por parte dos fiéis. (MC 23)\n"
            + "\n"
            + "“Em Maria a graça divina obteve plena vitória sobre o mal. Preservada de toda mancha de culpa, Ela é para nós, peregrinos sobre as estradas do mundo, luminoso exemplo de coerência evangélica”. (EK 1224)\n"
            + "\n"
            + "Oremos: (Oração inicial)\n"
            + "\n"
            + "Adoro-te, ó Pai nosso celeste, porque depuseste no seio puríssimo da Imaculada o teu Filho Unigênito.\n"
            + "\n"
            + "Adoro-te, ó Filho de Deus, porque te dignaste entrar no seio de Maria e te tornaste verdadeiro, real Filho seu.\n"
            + "\n"
            + "Adoro-te, ó Espírito Santo, porque te dignastes formar no seio Imaculado dEla o corpo do Filho de Deus.\n"
            + "\n"
            + "Adoro-te, ó Trindade Santíssima, ó Deus Uno na Santa Trindade, por ter enaltecido a Imaculada de um modo tão divino.\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo, como era no princípio, agora e sempre. Amém!\n"
            + "\n"
            + "Vamos dirigir nossos pedidos à Imaculada, nossa mãe amorosa, que está sempre pronta a escutar e acompanhar seus filhos:\n"
            + "\n"
            + "1 – Mãe querida, ajuda-nos a seguir teu Filho, amá-lo e anuncia-lo dignamente, usando de todos os recursos de que dispomos, nós te pedimos,\n"
            + "\n"
            + "R.: Virgem Maria, modelo de vida Evangélica, rogai por nós!\n"
            + "\n"
            + "2 – Para que manifestando o nosso amor a Ti, manifestemos também o amor à Igreja e sejamos fiéis aos seus ensinamentos, nós te pedimos,\n"
            + "\n"
            + "R.: Virgem Maria, modelo de vida Evangélica, rogai por nós!\n"
            + "\n"
            + "3 – Para que a Milícia da Imaculada, Tua obra, conte sempre com as orações e generosidade de seus mílites para ser canal de comunicação e formação e amor entre os irmãos, nós te pedimos,\n"
            + "\n"
            + "R.: Virgem Maria, modelo de vida Evangélica, rogai por nós!\n"
            + "\n"
            + "Pai Nosso...\n"
            + "\n"
            + "Ave Maria...\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo...\n"
            + "\n"
            + "Oh Maria, concebida sem pecado, rogai por nós que recorremos a vós e por todos quantos não recorrem a vós, especialmente pelos inimigos da Santa Igreja e por todos quantos são a vós recomendados.\n"
            + "\n"
            + "Oremos: (Oração final)\n"
            + "\n"
            + "Sob a tua proteção, ó Mãe dulcíssima, e com a invocação do mistério da tua Imaculada Conceição, desejo realizar todos os meus atos e suportar tudo o que me aconteça. Além disso, prometo contribuir, com todas as energias à minha disposição, para render a Deus o culto devido, por meio da difusão da devoção a Ti. Peço-te, portanto, ó Mãe amorosíssima, que te dignes ajudar-me em minhas fadigas. De minha parte, prometo, devota e livremente, como é justo, reconhecer como obtido de Deus por tua intercessão qualquer benefício que resulte das minhas atividades.\n"
            + "\n"
            + "Concede-me louvar-te, ó Virgem Santíssima; e dá-me força contra os teus inimigos! (EK 1353)";

    private String oitavoDia = "A Imaculada, o vértice do amor da criação\n"
            + "\n"
            + "“Desde a eternidade, Deus havia previsto uma Criatura que em nada teria se distanciado dEle” (EK 1224)\n"
            + "\n"
            + "A Imaculada é o sonho de Deus para a criação:\n"
            + "\n"
            + "“O vértice do amor da criação que retorna a Deus é a Imaculada, o ser sem mancha de pecado, toda formosa, toda de Deus. A sua vontade nem por um instante se afastou da vontade de Deus. Ela pertenceu-lhe sempre e de forma livre. E nela se realiza o milagre da união de Deus com a criação (EK 1310).\n"
            + "\n"
            + "Desde a eternidade, porém, Deus havia previsto uma Criatura que em nada, nem na menor coisa, teria se distanciado dEle, que não teria dissipado nenhuma graça, que não teria se apropriado de nenhuma coisa recebida dEle.\n"
            + "\n"
            + "“Em ti, ó Imaculada, a graça divina obteve plena vitória sobre o mal. Preservada de toda mancha de culpa, Tu és para nós, peregrinos sobre as estradas do mundo, luminoso exemplo de coerência evangélica”. (EK 1224)\n"
            + "\n"
            + "Oremos: (Oração inicial)\n"
            + "\n"
            + "Adoro-te, ó Pai nosso celeste, porque depuseste no seio puríssimo da Imaculada o teu Filho Unigênito.\n"
            + "\n"
            + "Adoro-te, ó Filho de Deus, porque te dignaste entrar no seio de Maria e te tornaste verdadeiro, real Filho seu.\n"
            + "\n"
            + "Adoro-te, ó Espírito Santo, porque te dignastes formar no seio Imaculado dEla o corpo do Filho de Deus.\n"
            + "\n"
            + "Adoro-te, ó Trindade Santíssima, ó Deus Uno na Santa Trindade, por ter enaltecido a Imaculada de um modo tão divino.\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo, como era no princípio, agora e sempre. Amém!\n"
            + "\n"
            + "Vamos dirigir nossos pedidos à Imaculada, nossa mãe amorosa, que está sempre pronta a escutar e acompanhar seus filhos:\n"
            + "\n"
            + "1 – Mãe querida, penetra em nosso coração para que possamos amar a Deus da forma como você amou, nós te pedimos,\n"
            + "\n"
            + "R.: Imaculada, vértice do amor da criação, rogai por nós!\n"
            + "\n"
            + "2 – Ó Imaculada, tu que esmagaste a cabeça da serpente, afaste de nós a tendencia ao mal, para que aspiremos à tua Beleza, à bondade e pureza de coração, nós te pedimos,\n"
            + "\n"
            + "R.: Imaculada, vértice do amor da criação, rogai por nós!\n"
            + "\n"
            + "3 – Para que todos nós, acolhendo teu amor de mãe, espelho do amor de Deus, possamos retribuir tudo quanto recebemos dEle, nós te pedimos,\n"
            + "\n"
            + "R.: Imaculada, vértice do amor da criação, rogai por nós!\n"
            + "\n"
            + "Pai Nosso...\n"
            + "\n"
            + "Ave Maria...\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo...\n"
            + "\n"
            + "Oh Maria, concebida sem pecado, rogai por nós que recorremos a vós e por todos quantos não recorrem a vós, especialmente pelos inimigos da Santa Igreja e por todos quantos são a vós recomendados.\n"
            + "\n"
            + "Oremos: (Oração final)\n"
            + "\n"
            + "Sob a tua proteção, ó Mãe dulcíssima, e com a invocação do mistério da tua Imaculada Conceição, desejo realizar todos os meus atos e suportar tudo o que me aconteça. Além disso, prometo contribuir, com todas as energias à minha disposição, para render a Deus o culto devido, por meio da difusão da devoção a Ti. Peço-te, portanto, ó Mãe amorosíssima, que te dignes ajudar-me em minhas fadigas. De minha parte, prometo, devota e livremente, como é justo, reconhecer como obtido de Deus por tua intercessão qualquer benefício que resulte das minhas atividades.\n"
            + "\n"
            + "Concede-me louvar-te, ó Virgem Santíssima; e dá-me força contra os teus inimigos! (EK 1353)";

    private String nonoDia = "A Imaculada – Eis o nosso Ideal\n"
            + "\n"
            + "“Devemos nos aproximar dela, ser semelhantes a Ela, que Ela viva e possa agir em nós e através de nós”\n"
            + "\n"
            + "Para São Maximiliano, a Imaculada era proposta como modelo de vida: “Devemos nos aproximar dela, tornarmo-nos semelhantes a Ela, permitir que Ela tome posse do nosso coração e de todo o nosso ser, que Ela viva, que possa agir em nós e através de nós, que Ela mesma ame Deus com o nosso coração, que nós pertençamos a Ela sem nenhuma restrição: Eis o nosso ideal” (EK 1210).\n"
            + "\n"
            + "“Maria Santíssima, digamos, Imaculada! inocente, estupenda, perfeita; a Mulher, a verdadeira Mulher ideal e real juntas; a criatura na qual a imagem de Deus se reflete com limpidez absoluta, sem qualquer turvamento, como ao contrário acontece com cada criatura humana” ...Não é talvez, fixando o nosso olhar sobre esta Mulher humilde, nossa irmã e também nossa celeste Mãe e Rainha, espelho nítido e sacro da infinita beleza... Esta beleza de Maria Imaculada não se torna para nós um modelo inspirador? Uma esperança confortadora? ... Tudo é novo, tudo é santo nesta criatura, cuja perfeição parece distancia-la sem comparação de nós, e cuja missão ao contrário, a aproxima de nós como irmã, como mãe, como esperança acessível a todos. (Paulo VI na homilia da solenidade da Imaculada em 1965, na conclusão do Concílio Vaticano II)\n"
            + "\n"
            + "\n"
            + "Oremos: (Oração inicial)\n"
            + "\n"
            + "Adoro-te, ó Pai nosso celeste, porque depuseste no seio puríssimo da Imaculada o teu Filho Unigênito.\n"
            + "\n"
            + "Adoro-te, ó Filho de Deus, porque te dignaste entrar no seio de Maria e te tornaste verdadeiro, real Filho seu.\n"
            + "\n"
            + "Adoro-te, ó Espírito Santo, porque te dignastes formar no seio Imaculado dEla o corpo do Filho de Deus.\n"
            + "\n"
            + "Adoro-te, ó Trindade Santíssima, ó Deus Uno na Santa Trindade, por ter enaltecido a Imaculada de um modo tão divino.\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo, como era no princípio, agora e sempre. Amém!\n"
            + "\n"
            + "Vamos dirigir nossos pedidos à Imaculada, nossa mãe amorosa, que está sempre pronta a escutar e acompanhar seus filhos:\n"
            + "\n"
            + "1 – Mãe querida, interceda junto a Jesus para a nossa consagração a Ti, nos fortaleça no empenho de, cada vez mais, viver conforte a vontade de Deus, nós te pedimos,\n"
            + "\n"
            + "R.: Ó Imaculada, nosso ideal, rogai por nós!\n"
            + "\n"
            + "2 – Por todos aqueles, que, vivendo o carisma idealizado por São Maximiliano se esforcem para serem cada mais semelhantes a Ti, nós te pedimos,\n"
            + "\n"
            + "R.: Ó Imaculada, nosso ideal, rogai por nós!\n"
            + "\n"
            + "3 – Pela Milícia da Imaculada, com todos os seus mílites, para que sejam presença significativa de ação pastoral em todos os ambientes, nós te pedimos,\n"
            + "\n"
            + "R.: Ó Imaculada, nosso ideal, rogai por nós!\n"
            + "\n"
            + "Pai Nosso...\n"
            + "\n"
            + "Ave Maria...\n"
            + "\n"
            + "Gloria ao Pai, ao Filho e ao Espírito Santo...\n"
            + "\n"
            + "Oh Maria, concebida sem pecado, rogai por nós que recorremos a vós e por todos quantos não recorrem a vós, especialmente pelos inimigos da Santa Igreja e por todos quantos são a vós recomendados.\n"
            + "\n"
            + "Oremos: (Oração final)\n"
            + "\n"
            + "Sob a tua proteção, ó Mãe dulcíssima, e com a invocação do mistério da tua Imaculada Conceição, desejo realizar todos os meus atos e suportar tudo o que me aconteça. Além disso, prometo contribuir, com todas as energias à minha disposição, para render a Deus o culto devido, por meio da difusão da devoção a Ti. Peço-te, portanto, ó Mãe amorosíssima, que te dignes ajudar-me em minhas fadigas. De minha parte, prometo, devota e livremente, como é justo, reconhecer como obtido de Deus por tua intercessão qualquer benefício que resulte das minhas atividades.\n"
            + "\n"
            + "Concede-me louvar-te, ó Virgem Santíssima; e dá-me força contra os teus inimigos! (EK 1353)";
}
