/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.santo.terco.novena;

import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Named;
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Felipe
 */
@Named
@SessionScoped
@Getter
@Setter
public class NovenaSantaTeresaJesusBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private String aprendizado = "Com a Novena de Santa Teresa D’Ávila aprendemos que a oração é o caminho que devemos seguir para nos encontrarmos com Cristo, para vivermos com Ele uma profunda intimidade. A oração de contemplação nos faz conhecer toda a humanidade de Jesus e, a partir daí, experimentar um crescimento e uma maturidade para vivermos o matrimônio Espiritual com o Amado Esposo. \n"
            + "\n"
            + "“A oração de intimidade com Deus não é outra coisa senão um morrer quase total a todas as coisas do mundo para alegrar-se só em Deus.”";

    private String primeiroDia = "Santa Teresa de Jesus nasceu em um lar cristão e desde criança foi chamada a viver só para Deus. O pai era um homem muito caridoso com os pobres e piedoso com os doentes. Ninguém jamais o viu murmurar ou praguejar. Sua mãe, devota de Nossa Senhora, ensinou-lhe a recitar o rosário. Herdou também de sua mãe o gosto pela leitura de histórias de santos e, também histórias de cavalaria. Histórias estas que influenciaram sua vida. \n"
            + "\n"
            + "As histórias de martírio de algumas santas levaram Teresa e seu irmão a desejarem fugir para a terra dos mouros para morrerem decapitados, pois queriam gozar tão logo dos bens celestes. Percebendo que isso era impossível, queriam, então, ser eremitas. Nas brincadeiras com as amigas, gostava de fazer mosteiros, como se fosse uma monja.\n"
            + "Com a perda de sua mãe, tomou Maria por mãe e, a partir de então, começou a entender as graças que o Senhor lhe concedia, e o quanto a Sua Majestade queria que fosse toda dEle. Esta descoberta a fez ofendê-Lo, ao invés de dar-Lhe graças. \n"
            + "\n"
            + "Deixou-se encantar pelos prazeres do mundo, pela vaidade exagerada, pelas companhias dos primos e pelas conversas e entretenimentos levianos. A amizade com uma parenta foi lhe transformando a tal ponto que quase nada lhe restou de sua inclinação natural para a virtude, seus hábitos foram lhe imprimidos. Dizia que sua alma começou a não resistir ao que lhe causava todo mal. Perdeu o temor de Deus e com o medo de também perder a honra, tudo que fazia lhe trazia aflição. Pensando que não seria descoberta, atreveu-se a fazer coisas contra a honra e contra Deus. Mas era impossível ocultar algo de quem tudo vê. Mesmo vivendo desta forma não se entregou a pecados graves. Deus a livrou, contra a sua própria vontade, de se perder por inteira. \n"
            + "\n"
            + "O pai desgostoso com a situação e as suas companhias colocou-a no convento das monjas agostinianas. No início foi difícil a adaptação, mas aos poucos foi encontrando com a sua essência, suas virtudes, e a cada dia foi renascendo no seu coração o amor a Deus e o desejo de nunca mais ofendê-Lo. Acreditava que a Sua Majestade buscava incessantemente a melhor maneira de trazê-la a Si. Dizia: “Bendito sejais, Senhor, que tanto sofrestes por mim.”\n"
            + "\n"
            + "Vossa sou, pois me criastes,\n"
            + "Vossa, porque me remistes,\n"
            + "Vossa, porque me atraístes,\n"
            + "E porque me suportastes\n"
            + "E me salvastes, por fim:\n"
            + "Que mandais fazer de mim?\n"
            + "Reflexão\n"
            + "1.    Santa Teresa experimentou o bem e o mal. Quis ser mártir, depois eremita, e ao descobrir sua vocação – ser toda de Deus – preferiu fugir buscando os prazeres do mundo, a vaidade, as más companhias. Assumo minha vocação acolhendo as verdades de Deus ou me escondo nas coisas que dão prazer à minha carne? \n"
            + "\n"
            + "2.     Mesmo vivendo daquela forma, Deus a livrou de se perder por inteira, pois a queria perto de Si. Santa Teresa se abriu ao toque de amor de Deus, à Sua misericórdia, desejando não mais ofendê-Lo. Abro-me sem reservas a esse toque de amor de Deus?\n"
            + "\n"
            + "Oração\n"
            + "Santa Teresa d’Àvila, vós que lutastes contra os desejos da carne para assumir o chamado de ser toda de Deus, fazei com que eu permita que o toque de Deus transforme o meu interior e desperte em mim o desejo de não mais ofendê-lo. Amém. \n"
            + "\n"
            + "Pai Nosso, Ave Maria, Glória.\n"
            + "Santa Teresa d’Ávila, rogai por nós.";

    private String segundoDia = "A dor como caminho para encontro com Deus\n"
            + "Uma monja começou a falar a Santa Teresa como decidira ser monja e a recompensa dada pelo Senhor a quem tudo deixa por Ele. Encantava-se com sua conversa santa, porém, tinha aversão à ideia de ser uma monja. Seu coração estava tão duro que nem mesmo a leitura da Paixão lhe arrancava uma única lágrima. Em oração, pediu ao Senhor que lhe indicasse o melhor caminho para servi-Lo. Queria se dedicar a Deus, mas não estava convencida a fazê-lo, pois ainda se entregava mais ao que agradava à sua carne e à vaidade. \n"
            + "\n"
            + "O Senhor lhe deu uma grave doença que a fez retornar à casa paterna. Curada foi visitar uma irmã. No caminho, ficou por alguns dias na casa de um tio. Tempo suficiente para que as palavras de Deus que ouvia e lia, e a sua companhia fizessem-na compreender as verdades da inutilidade das coisas do mundo, a vaidade exagerada e a rapidez de como tudo passa. Decidiu abraçar a vocação, mesmo com medo de não suportar as renúncias e exigências da vida religiosa.\n"
            + "\n"
            + "Havia grande contentamento em ser monja, era querida por todos e dedicada em tudo que fazia. Ocupava-se sempre das coisas que dava prazer. No Carmelo, uma monja sofria de uma grave e dolorosa enfermidade, mas suportava tudo com paciência. Vendo-a assim, Santa Teresa pediu a Deus que lhe concedesse a mesma paciência. O Senhor atendeu o seu pedido. Sua enfermidade durou três anos. Foram meses de muita dor, sofrimento e de luta pela vida. Mas a dor maior estava em se ver tão pecadora e pequena diante da grandeza do amor de Deus.\n"
            + "\n"
            + "Levada para a casa de seu pai teve um paroxismo tão forte que ficou sem sentido por quatro dias. Sua morte era esperada, tanto que se prepararam para o funeral, mas Sua Majestade a fez recuperar o sentido; então, imediatamente buscou a confissão e a comunhão. Naquela hora recebeu a graça de jamais deixar de confessar qualquer coisa que considerasse pecado, mesmo que fosse venial.\n"
            + "\n"
            + "Pediu que a levassem de volta ao mosteiro, mesmo naquele estado: pior que um morto. Tendo melhorado, ficou paralítica por longo tempo, mas grande era sua conformidade com a vontade de Deus, que suportava todo o sofrimento com alegria. Queria muito ser curada para melhor servir a Deus, contudo, o Senhor sabe o que é o melhor para cada um. Os médicos pouco podiam fazer.\n"
            + "\n"
            + "Resolveu, então, pedir a S. José, o pai de Jesus. Recebeu a graça que tanto queria, mas isso não a fez perseverar no caminho. Deus dava a ela a graça de fazer o bem, mas o fazia com imperfeições e faltas. Recaiu na vaidade depois de tantas bênçãos recebidas. A mão de Deus continuava a lhe sustentar e fazer com que voltasse a se levantar.\n"
            + "\n"
            + "“Busca-me em ti, não por fora…\n"
            + "para me achares ali, \n"
            + "chama-me, que,  a qualquer hora, \n"
            + "a ti virei sem demora…”\n"
            + "Reflexão\n"
            + "1. Encantou-se com a história da monja, mas isso não foi suficiente para levá-la a assumir sua vocação, pois tinha medo das renúncias e exigências da vida religiosa.  O encantamento pelo carisma do qual pertenço, me fez deixar tudo e assumir uma vocação. Hoje abraço esse chamado assumindo as dores do servir e das renúncias?\n"
            + "\n"
            + "2. Toda enfermidade que sofreu foi para prová-la na paciência de tudo sofrer por amor.  Viu-se tão pequena e pecadora diante da misericórdia de Deus e Sua fidelidade àqueles que são escolhidos. O Senhor usou desta enfermidade para que ela O encontrasse dentro de si. Aceito as dores como caminho para o encontro íntimo com Deus, comigo mesmo e minhas misérias?\n"
            + "\n"
            + "Oração\n"
            + "Santa Teresa d’Ávila, vós que, pela dor e pela enfermidade, encontrastes com amor  e a misericórdia de Cristo, fazei que eu, ao assumir o chamado de Deus, faça do sofrimento o caminho seguro para o encontro e pessoal  e íntimo com  Cristo. Amém.          \n"
            + "\n"
            + "Pai Nosso, Ave Maria, Glória. \n"
            + "Santa Teresa d’Ávila, rogai por nós.";

    private String terceiroDia = "Batalha entre Deus e o mundo\n"
            + "É importante para as almas entenderem que quando se inicia uma vida de oração é preciso se desapegar de toda espécie de prazer, e entrar num caminho voltado somente para ajudar Cristo a carregar a Sua cruz, apenas como um bom cavaleiro, sem pagamento algum, apenas pelo prazer de servir o seu Rei. É fundamental seguir com determinação e sem querer consolações; o caminho é a cruz: “toma a tua cruz e segue-me”. \n"
            + "\n"
            + "Santa Teresa travou uma grande batalha entre lidar com Deus e lidar com o mundo. Não se rejubilava em Deus, nem se alegrava no mundo. Somente com as misericórdias de Deus é que teve ânimo para orar. Dos vinte e oito anos de oração, passou mais de dezoito nessa luta. \n"
            + "\n"
            + "Sua alma, já cansada, entrou um dia no oratório, viu a imagem de um Cristo com grandes chagas que inspirava tamanha devoção, que ela ficou extremamente perturbada, visto que a imagem representava bem o que Jesus passou por nós. Foi tão grande o sentimento de ter sido mal–agradecida àquelas chagas que o seu coração quase partiu. Imediatamente lançou-se aos Seus pés, em lágrimas, suplicou que a fortalecesse para que não O ofendesse mais.\n"
            + "\n"
            + "Naquele momento depositou toda a sua confiança em Deus. Em oração se esforçava por representar Cristo dentro de si e se sentia melhor nas passagens onde O via mais sozinho. Na oração do Horto, fazia-Lhe companhia; ficava pensando no suor e na aflição que sofrera, desejando se possível for, enxugar-Lhe o suor tão doloroso. Mas, não ousava fazer, pois vinham em sua mente os pecados cometidos. Por longos anos, quase todas as noites, antes de dormir, ao se encomendar a Deus, pensava na oração do Horto, pois era um costume que adquiriu antes mesmo de ser monja.  \n"
            + "\n"
            + "Santa Teresa pediu a Sua Majestade um remédio para viver sem muito sobressalto nessa guerra tão perigosa. Disse Ele ser o amor e o temor, pois o amor nos fará apressar o passo e o temor nos levará a nos atentar por onde colocamos nossos pés, para que não caiamos em uma trilha tão pedregosa, assim não seremos enganados. Dizia às suas filhas espirituais que, quem ama genuinamente a Deus não pode amar a vaidade, a riqueza, as coisas do mundo, os deleites, as honras ou ter contendas ou inveja. Tudo porque a única coisa que devemos pretender é contentar o Amado, desejando ardentemente ser amado por Ele, empenhando a vida em atender como agradá-Lo mais. \n"
            + "\n"
            + "“Ditoso o coração enamorado\n"
            + "Que só em Deus coloca o pensamento;\n"
            + "Por ele renuncia a todo criado,\n"
            + "Nele acha glória, paz, contentamento…”\n"
            + "Reflexão\n"
            + "1. Santa Teresa passou longos anos de sua vida travando uma luta entre Deus e o mundo. Pela misericórdia de Deus não se afastou da vida de oração, mas encontrou nela forças para renunciar ao mundo e ajudar Cristo a carregar a Sua cruz. A minha oração me impulsiona a dizer sim a Deus, colocando-me a serviço de Cristo sem nada esperar, pelo simples prazer de servir?\n"
            + "\n"
            + "2. A experiência com Jesus crucificado e Suas chagas fez Santa Teresa experimentar toda dor da Paixão de Cristo e Sua solidão. Nesse momento, entendeu a dimensão do amor perfeito e pleno, e o quanto precisa lutar para amar genuinamente a Deus e não o que dá prazer à carne. Ao olhar para Jesus crucificado, contemplando a Sua dor, vejo a necessidade que tenho de ser inteiro em Cristo?\n"
            + "\n"
            + "Oração\n"
            + "Santa Teresa d’Ávila, vós que lutastes para ser serva de um único Rei, Jesus Cristo, fazei com que eu, contemplando a Paixão de Jesus, experimente o verdadeiro amor que nasce do Seu Sagrado Coração e das Suas chagas,  e viva em plenitude a minha consagração. Amém.\n"
            + "\n"
            + "Pai Nosso, Ave Maria, Glória. \n"
            + "Santa Teresa d’Ávila, rogai por nós.";

    private String quartoDia = "Cruz, sinal do amor a Deus\n"
            + "Em suas orações o Senhor lhe concedia a graça de vê-Lo, de ouvir a Sua voz. Aparecia-lhe de várias formas, dependendo do modo que se encontrava. Quando passava por tribulações, para revigorá-la, mostrava-Se com as chagas, na Cruz ou no Horto.\n"
            + "\n"
            + "A Sua Majestade concedia à Santa visões celestiais que não eram bem interpretadas por alguns mestres, por isso, davam-lhe mal conselho. Por pensarem que fosse obra do demônio e para livrá-la do mal, ordenavam-lhe que fizesse figa, o sinal-da-cruz e se opusesse à cruz. Obedecia, mas era um grande sofrimento para ela. Para não fazer o sinal-da-cruz a todo tempo, segurava na mão a cruz do rosário.\n"
            + "\n"
            + "Certo dia, estando com ela na mão, o Senhor a tomou em Suas mãos e quando lhe devolveu estava formada por quatro pedras grandes muito mais preciosas que diamantes. As cinco chagas estavam formosamente cravejadas na cruz.  Assim o Senhor lhe pediu que sempre visse a cruz: no lugar da madeira as pedras. Esta visão só ela tinha.\n"
            + "\n"
            + "Dizia às suas filhas que o Senhor quer levar como almas fortes àqueles que buscam a contemplação, dando a eles a cruz que Sua Majestade sempre teve. A cruz que não é leve, e se soubessem o caminho e maneiras pelos quais Deus lhes dá essa cruz se espantariam; muitos não suportariam os sofrimentos dados se não fossem as consolações recebidas.\n"
            + "\n"
            + "É absurdo crer que o Senhor admita ter como amigos íntimos pessoas comodistas e que não sofrem. Os caminhos dos contemplativos são ásperos, cheios de irregularidades, fazendo-os por vezes pensar que se perdem e que devem recomeçar a percorrer os trechos já percorridos, sendo necessário que Ele os dê mantimentos; não água, mas vinho, pois embriagados não se atentem por aquilo que passam e suportem as dores.\n"
            + "\n"
            + "Para Santa Teresa, a tarefa dela e de suas monjas é de se apegar à cruz que o Esposo tomou sobre si. Aquela que mais puder padecer, que padeça mais por Ele e será a que melhor se libertará.  O maior favor que o Senhor pode lhes dar é uma vida que imita a vida de Seu Filho tão amado. As graças recebidas visa fortalecer as suas fraquezas, assim poderão imitá-Lo no sofrimento. \n"
            + "\n"
            + "“O consolo está, e a vida, \n"
            + "Só na cruz;\n"
            + "E ao Céu é a única senda \n"
            + "Que conduz.”\n"
            + "Reflexão\n"
            + "1. Santa Teresa diz que o caminho para aqueles que buscam a contemplação é a cruz, pois por ela se experimenta a dor, o sofrimento, a renúncia, mas ao mesmo tempo o consolo de Deus. O caminho que percorro na minha consagração tem sido marcado pela dor e sofrimento que emanam da cruz de Cristo?\n"
            + "\n"
            + "2. A tarefa de Santa Teresa e de suas monjas é de se apegar à cruz que o Esposo tomou sobre Si, para que suas vidas sejam uma imitação da vida de Cristo.  A cruz que carrego hoje me leva à identificação com Cristo, com Sua dor e o abandono na vontade de Deus?\n"
            + "\n"
            + "Oração\n"
            + "Santa Teresa d’Ávila, vós que vencestes os prazeres da carne para assumir a cruz de Cristo, as Suas dores e os Seus sofrimentos, fazei que eu abrace com amor e determinação a cruz, que é o caminho para a glória e a estrada para o céu. Amém.\n"
            + "\n"
            + "Pai Nosso, Ave Maria, Glória. \n"
            + "Santa Teresa d’Ávila, rogai por nós.";

    private String quintoDia = "Pobreza\n"
            + "O Senhor já lhe dera o desejo de pobreza, desejo de, mesmo no seu estado, pedir esmola por amor a Deus, de não ter casa ou qualquer outra coisa. Mas pensava que talvez as monjas não tivessem esse mesmo desejo. Muita coisa ouvia sobre esse assunto e inquietava o seu coração. Um dia estando em oração, ao olhar Cristo na cruz tão pobre e desnudo, não suportou a ideia da riqueza.\n"
            + "\n"
            + "Suplicava-Lhe em lágrimas que fizesse as coisas de maneira que viesse a ser tão pobre quanto Ele. Insatisfeita com o voto de pobreza que se seguia no mosteiro, questionou algumas pessoas sobre qual seria a melhor forma para vivê-lo, mas não recebeu o apoio que desejava. Entregou o caso à Sua Majestade que lhe pediu para não deixar de estabelecer o mosteiro na pobreza, pois esta era vontade de Seu Pai e Sua, e que lhe ajudaria.\n"
            + "\n"
            + "Muitas monjas temiam passar fome, por isso, ensinava que viver a pobreza é ter a certeza que nada vai lhes faltar, que o sustento vem do Senhor, e que Ele dará o próprio alimento. Assim, que não se preocupassem com a renda e com o alimento, mas deixassem isso com o Senhor dos ricos e da riqueza. Estava certa que a promessa de Deus, feita um dia a ela, não deixaria de ser cumprida. \n"
            + "\n"
            + "Conceituava que a pobreza é um bem que traz em si todos os bens do mundo; uma grande soberania. Dizia que quem deseja honra tem interesse por rendas ou dinheiro; mas quem é pobre, mesmo que mereça honra para si, é pouco considerado. Suas casas eram pobres em tudo e pequenas, assemelhando-se em algo no Rei que teve por casa apenas o presépio de Belém onde nasceu, e a cruz onde morreu.  \n"
            + "\n"
            + "Considerava que além de se viver a pobreza material deveria se viver a pobreza espiritual. Nas horas de tribulação, de intranquilidade, nas perseguições, nos sofrimentos e nos tempos de aridez encontrava em Cristo o bom amigo, porque O via como Homem, permanecendo em sua companhia. Para ela o Senhor se viu privado de todo consolo, restando-lhe apenas os sofrimentos; não desejava, então deixá-Lo só, fazendo-O sofrer mais.\n"
            + "\n"
            + "A verdadeira pobreza de espírito consiste em não buscar consolo nem prazer na oração, mas consolações nos sofrimentos, por amor Àquele que sempre viveu em meio a eles, e em ter paz nos sofrimentos e securas. Mesmo que sinta alguma coisa, a alma não deve se inquietar ou perturbar, como fazem certas pessoas que consideram tudo perdido se não tiverem sempre trabalhando com o intelecto e sentindo fervor.\n"
            + "\n"
            + "“A pobreza é a estrela real\n"
            + "Que o Imperador celestial\n"
            + "Trilhou com todo o desvelo,\n"
            + "Monjas do Carmelo.”\n"
            + "Reflexão\n"
            + "1. Ao ver Cristo na cruz, pobre e desnudo, não suportou a ideia da riqueza, por isso, suplicou-Lhe que a ajudasse a viver a mesma pobreza de Cristo no Carmelo. Vivo a pobreza, o desprendimento dos bens materiais, confiando na providência divina?\n"
            + "\n"
            + "2. A verdadeira pobreza espiritual, segundo Santa Teresa, consiste em encontrar em Deus a consolação nos sofrimentos, e em ter paz nos momentos de dores e securas. Nos momentos de sofrimentos, solidão, aridez, tribulações, busco o consolo em Deus encontrando em Cristo o verdadeiro e bom amigo?\n"
            + "\n"
            + "Oração\n"
            + "Santa Teresa de Jesus, vós que vivestes a pobreza material e espiritual, encontrando em Sua Majestade o consolo e ajuda adequada nos momentos de sofrimento e aridez, fazei com que eu, livre de todos os bens terrenos e abraçando a cruz de Cristo, assuma a verdadeira pobreza que nasce do coração de Deus. Amém.\n"
            + "\n"
            + "Pai Nosso, Ave Maria, Glória. \n"
            + "Santa Teresa d’Ávila, rogai por nós.";

    private String sextoDia = "O amor a Deus e aos irmãos\n"
            + "É extremamente importante o amor entre os irmãos, pois assim não haverá problema que não seja resolvido com facilidade. Se este mandamento fosse respeitado pelos homens muito favorecia a guarda do outro. Contudo, por excesso ou por falta, nunca se chega a guardá-lo com perfeição.\n"
            + "\n"
            + "Santa Teresa trata o amor de duas maneiras: a primeira é espiritual e nada tem a ver com os sentidos, nem com a ternura da nossa natureza a ponto de ser privada de sua pureza; a segunda, também é espiritual, mas sendo acompanhada da nossa sensibilidade e da nossa fraqueza. Quem se deixa instruir pelo Senhor na oração ou a quem Ele deseja instruir, essa pessoa ama de modo distinto, diferente daquele que não chegou a esse ponto.\n"
            + "\n"
            + "Dizia às suas filhas: não se contente em amar pelo corpo e por seus atrativos exteriores. Ame pelo fato de amar, sem se importar se serão amadas. Podendo ocorrer, a princípio, que se inclinem a gostarem de ser amadas, mas depois vão perceber que isso é um disparate, caso isso não traga proveito algum à alma, seja na doutrina ou na oração.\n"
            + "\n"
            + "O amor verdadeiro para Santa Teresa é com mais paixão e mais proveitoso, pois as almas sempre cuidam mais em dar do que de receber, agindo assim mesmo diante do Criador. Quando amam alguém, as almas perfeitas têm desejo de que ele seja digno do amor de Deus, porque só assim podem continuar a amá-Lo. \n"
            + "\n"
            + "“Quanto mais se pratica o amor ao próximo, tanto mais se estará praticando amor a Deus. Isso porque é tão grande o amor que o Senhor nos tem que, para recompensar aquele que demonstramos pelo próximo, faz crescer por mil maneiras o amor que temos a Ele”.\n"
            + "\n"
            + "“O amor que é mundano\n"
            + "Se apega a esta vida;\n"
            + "Mas o amor divino\n"
            + "À outra nos convida.\n"
            + "Sem ti, Deus eterno,\n"
            + "Quem pode viver?”\n"
            + "Reflexão\n"
            + "1. É extremamente importante amar uns aos outros, pois assim não haverá problema que não seja resolvido com facilidade, diz Santa Teresa. O amor que sinto pelos meus irmãos me leva a derrubar as barreiras da indiferença, do orgulho e do egoísmo?\n"
            + "\n"
            + "2. Quanto mais se pratica o amor ao próximo, tanto mais se estará praticando o amor a Deus. Amar o outro sem nada desejar em troca. Como vivo esta realidade na minha vida fraterna e na missão?\n"
            + "\n"
            + "Oração\n"
            + "Santa Teresa de Jesus, vós que vivestes o amor perfeito, que amastes o outro sem esperar ser amada ou receber algo em troca, fazei que eu me deixe ser instruída pela Sua Majestade para alcançar esse amor perfeito. Amém.\n"
            + "\n"
            + "Pai Nosso, Ave Maria, Glória. \n"
            + "Santa Teresa d’Ávila, rogai por nós.";

    private String setimoDia = "Oração – encontro com o Amigo íntimo\n"
            + "Desde que entrara para o Carmelo sua saúde não foi muito estável, chegando quase à morte. Por 20 anos tinha vômitos pela manhã, sendo impedida de alimentar-se até o meio dia. Como comungava diariamente, durante à noite, provocava-o para que seu mal estar não fosse pior. Apesar de todos esses males era alegre, pois tinha a impressão de com isso estava a servir o Senhor de alguma maneira.\n"
            + "\n"
            + "Para ela na doença e em situações difíceis, a alma que ama tem como verdadeira oração fazer a dádiva dos seus sofrimentos, lembrar daqueles por quem os padece, conformar-se com as suas dores. Trata-se, portanto, do exercício do amor, pois somos obrigados a orar quando temos momentos de solidão, porque se estes nos faltam, mesmo assim se pode orar. O Senhor nos tira o tempo da oração com sofrimentos, mas consegue-se obter lucros com esses momentos.\n"
            + "\n"
            + "Santa Teresa nos ensina o caminho da oração. Este caminho começa por estar a sós, somente na companhia do próprio Mestre, pois Ele com amor e humildade é que nos ensina a orar. Para ela é preciso ter os nossos olhos nos Seus olhos, pois Ele está sempre a nos olhar, suportando as abominações que praticamos contra Ele.\n"
            + "\n"
            + "Ela compara a cada uma de suas filhas a uma esposa bem casada que se mostra triste quando vê o esposo triste e alegre quando o vê alegre, mesmo que não esteja. Se estivermos alegres, vejamo-Lo ressuscitado, pois o simples imaginar que saiu do sepulcro nos alegrará. Se estivermos tristes, vejamo-lo a caminho do Horto; pensemos na tamanha aflição de Sua alma.\n"
            + "\n"
            + "Podemos vê-Lo atado às colunas, cheio de dores, com a carne feita em pedaços, sofrendo muito; perseguido por uns, cuspido por outros, renegados pelos amigos, desamparado por eles, sem ninguém que O defendesse, gelado de frio, posto em imensa solidão. Teresa pedia: contemplai o Senhor carregando a cruz, sem que O deixassem recobrar o fôlego; com os olhos cheios de lágrimas, esquecendo de Suas dores para consolar as nossas.\n"
            + "\n"
            + "Ela chama suas filhas para carregar a cruz de Cristo, para que Ele não siga tão carregado, não se incomodando com os judeus que as atropelam; não se importando com o que dizem e fazendo-se de surdas aos murmúrios; tropeçando ou caindo com o Esposo não devem se afastar e nem deixar a cruz.\n"
            + "\n"
            + "“Sem tal companhia\n"
            + "Vejo me cativo.\n"
            + "Sem ti, vida minha,\n"
            + "É morte o que eu vivo.”\n"
            + "Reflexão\n"
            + "1. Santa Teresa fez de sua oração um encontro pessoal e íntimo com Jesus, mergulhando em Suas alegria, dores e sofrimentos. Contemplando a vida, morte e ressurreição de Cristo, caminho para a união plena com o Amado, tornando-me um com Ele?\n"
            + "\n"
            + "2. Santa Teresa fez da dor uma oração, conformando a sua vontade com a vontade de Deus, entendendo que mesmo naquela situação era chamada a servir. A minha oração é de um verdadeiro abandono à vontade de Deus, assumindo a vocação de serva de Sua Majestade, não parando nas minhas limitações e dores?\n"
            + "\n"
            + "Oração\n"
            + "Santa Teresa d’Ávila, vós que fizestes da oração o caminho perfeito para viver a união plena com o Amado, fazei com que eu, por meio do encontro íntimo com Jesus, identificando-me com Suas dores e sofrimentos, abrace com amor a cruz que sou chamado a carregar, vivendo em plenitude a união espiritual com Cristo. Amém. \n"
            + "\n"
            + "Pai Nosso, Ave Maria, Glória. \n"
            + "Santa Teresa d’Ávila, rogai por nós.";

    private String oitavoDia = "Matrimônio Espiritual\n"
            + "Estando um dia no Convento da Encarnação, ao receber a comunhão, o padre João da Cruz, partiu a Hóstia para a outra irmã. Pensou ela que era por falta de Hóstia, mas ele queria mortificá-la, pois havia dito a ele, anteriormente, que gostava muito quando as Hóstias eram bem grandes. Ouviu naquele dia de Sua Majestade: “não tenhas medo, filha, que alguém tenha poder de afastar-te de Mim”.\n"
            + "\n"
            + "O Senhor apresentou-se, no seu íntimo, dando-lhe a Sua mão direita dizendo: “Olha este prego, que é sinal de que serás Minha esposa de hoje em diante. Até agora não o tinhas merecido; doravante, defenderás Minha honra não só como Criador, como Rei e como teu Deus, mas como verdadeira esposa Minha: Minha honra é a tua, e a tua, Minha.”\n"
            + "Tamanha foi sua alegria que ficou como que desatinada e disse ao Senhor que ou aumentasse a sua baixeza ou não a concedesse tão infinita graça, pois certamente não lhe parecia que a sua natureza pudesse suportar.\n"
            + "\n"
            + "No matrimônio espiritual a união secreta se passa no centro mais íntimo da alma, que deve ser onde está o próprio Deus. Não precisa de porta para entrar, porque em todas as graças, os sentidos e as faculdades parecem servir de intermediários, o mesmo devendo acontecer com esse aparecimento da Humanidade do Senhor. Ele aparece no centro da alma sem visão imaginária, mas intelectual, tal como surgiu aos Apóstolos, sem entrar pela porta, e lhes disse: “a paz esteja convosco”.\n"
            + "\n"
            + "O Matrimônio espiritual é como se a água caísse do céu sobre um rio ou uma fonte, confundindo-se então todas as águas. Já não se sabe o que é água do rio ou água que cai do céu. “Quem se une ao Senhor torna-se com ele um só espírito”, talvez São Paulo esteja se referindo a união da alma com o seu Esposo. Sem dúvida, a alma que se esvazia de tudo o que é criado e desapega-se dele por amor a Deus, o próprio Senhor a preenche de Si mesmo.\n"
            + "\n"
            + "“Eis aqui meu coração:\n"
            + "Deponho-o na vossa palma;\n"
            + "Minhas entranhas, minha alma,\n"
            + "Meu corpo, vida e afeição.\n"
            + "Doce Esposo e Redenção,\n"
            + "A vós entregar-me vim:\n"
            + "Que mandais fazer de mim?\n"
            + "Reflexão\n"
            + "1. A alma que se esvazia de tudo que é criado e se desapega dele por amor a Deus é preenchida pelo seu Senhor, tornando-se uma com Ele. O que mais me impede hoje de viver essa união plena com o meu Amado?\n"
            + "\n"
            + "2. Santa Teresa se tornava naquela Eucaristia uma só em Cristo. Sua alma, sua vida não mais pertencia a si mesma, mas era toda de Deus. Os passos que dou na vida consagrada estão me levando a ser inteira de Deus, estão me levando a viver esse matrimônio espiritual?\n"
            + "\n"
            + "Oração\n"
            + "Santa Teresa d’Ávila, vós que lutastes contra o desejo da carne, contra vossos apegos para assim viver a união plena com o Amado, fazei que eu esvazie, a cada dia, a minha alma de tudo que é criado para que o meu coração seja preenchido somente pelo meu Senhor, tornando-me assim Sua Esposa. Amém.\n"
            + "\n"
            + "Pai Nosso, Ave Maria, Glória. \n"
            + "Santa Teresa d’Ávila, rogai por nós.";

    private String nonoDia = "Maria, Mãe das Carmelitas\n"
            + "Um dia no mosteiro, conversando com outras monjas, nasceu a ideia de viverem segundo as regras primitivas do Carmelo. Resolveram colocar todos os planos e projetos nas mãos de Deus. Certa vez, após a comunhão, o Senhor lhe ordenou expressamente que se dedicasse a esse empreendimento com todas as suas forças, prometendo-lhe que o mosteiro não deixaria de ser feito e dizendo que ali seria muito bem servido. Este devia ser dedicado a S. José, pois este santo glorioso guardaria uma porta, Nossa Senhora, a outra, e Cristo andaria ao seu lado; e a casa seria uma estrela da qual sairia um grande resplendor.\n"
            + "\n"
            + "Começou, então, a construção do mosteiro de S. José. Muitos foram os problemas, as tribulações e perseguições para que ela desistisse. Mas se manteve firme e em silêncio diante dos ataques; sempre esperando em Deus. Achava que aquele espaço não seria adequado, pensou em ampliá-lo, mas o Senhor não permitiu, pois queria que este fosse pequeno e que ali se vivesse a pobreza. \n"
            + "\n"
            + "No dia de Nossa Senhora da Assunção, considerando seus inúmeros pecados veio-lhe um arroubo imenso, sentou-se naquele momento e teve a impressão que alguém lhe cobria com uma roupa de grande brancura e esplendor. No início não via quem fazia isso, depois percebeu que era Nossa Senhora do seu lado direito e S. José, do esquerdo adornando-a com aquelas vestes, purificando-a dos seus pecados.\n"
            + "\n"
            + "Maria dizia que se contentava em vê-la servindo ao glorioso S. José e que o mosteiro se faria de acordo com o seu desejo e que os dois seriam muito bem servidos ali. Pediu para que nada temesse, pois o seu Filho prometera andar ao seu lado.\n"
            + "\n"
            + " Até conseguir a licença para ir para o Mosteiro de S. José foram muitas batalhas travadas com o demônio que usava de todas as armas para combatê-la, mas sentiu consolada quando lá chegou. Numa festa da Assunção da Rainha dos Anjos e Senhora Nossa, o Senhor quis lhe fazer um favor apresentando-lhe a Sua subida ao céu, a alegria e a solenidade com que Ela foi recebida, bem como  o lugar onde está. O seu espírito teve enorme exultação ao contemplar a imensa glória. Isso fez com que santa Teresa desejasse cada vez mais suportar grandes sofrimentos e servir a essa Senhora, que tanto mereceu.\n"
            + "\n"
            + "Sabia que era preciso confiar nos méritos de Jesus e de Sua Mãe para vencer as batalhas. Sentia-se muito indigna de vestir o hábito de Sua Mãe, mas pedia a todas as suas filhas que louvassem por ele, porque eram verdadeiramente filhas dessa Senhora. E que deviam sempre imitá-La e considerar a imensa grandeza dessa Senhora, bem como a vantagem de tê-la por padroeira; pois nem seus grandes pecados e o fato de ser como era podiam ofuscar minimamente essa sagrada Ordem.\n"
            + "\n"
            + "“Seu Único Filho \n"
            + "O Pai nos envia\n"
            + "Nasce hoje na lapa,\n"
            + "Da Virgem Maria.\n"
            + "Reflexão\n"
            + "1. Santa Teresa via Maria como mãe e protetora, pois em todos os momentos recorreu a Ela e foi prontamente atendida. Na minha vida de consagrado encontro em Maria a proteção, o consolo, a direção?\n"
            + "\n"
            + "2. Santa Teresa pedia que suas monjas considerassem grande honra ter Nossa Senhora como padroeira e que, como filhas dessa boa Mãe, louvassem a Deus pelo hábito que traziam e que a imitassem sempre. Busco em Maria as virtudes necessárias para bem servir Jesus Cristo?\n"
            + "\n"
            + "Oração\n"
            + "Santa Teresa d’Ávila, vós que encontrastes em Maria a proteção, o consolo, o caminho que vos levaria a Jesus, fazei que eu, conduzido pelas mãos da Mãe da Luz da Vida, resplandeça a verdadeira luz que ilumina as trevas do mundo. Amém.\n"
            + "\n"
            + "Pai Nosso, Ave Maria, Glória. \n"
            + "Santa Teresa d’Ávila, rogai por nós.";
}
