server.port=${PORT:8080}
joinfaces.faces-servlet.url-mappings=*.xhtml, /faces/*

# Expondo o actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
server.port=8080
